### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by rohithill**
There was typo in command.

### CODE REVIEW

**Comment by srbcheema1** [comment]
nice catch @rohithill  :)
just a small ammendment is required
actually you will need to append new path location to older one not to rewrite it .

it will become `export PATH=$PATH:"$HOME/.local/bin"`

**Comment by srbcheema1** [comment]
Also you can do the same fix in https://github.com/srbcheema1/CoolKit

**Comment by rohithill** [comment]
Then it will become probably `export PATH="$PATH:$HOME/.local/bin"`  (observe the quotes)
My pull request doesn't overwrite, it appends.

**Comment by srbcheema1** [comment]
both the ways are correct. but I prefer the second one. it seems correct according to syntax of many other languages.

**Comment by rohithill** [comment]
> nice catch @rohithill :)
> just a small ammendment is required
> actually you will need to append new path location to older one not to rewrite it .
> 
> it will become `export PATH=$PATH:"$HOME/.local/bin"`

This works fine.

**Review by srbcheema1 — APPROVED** [review]

**Pull request merged**
