### PR TITLE
video trim

### PR DESCRIPTION
**Pull request by ujjawalgupta29**

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks @ujjawalgupta29 for the PR.
It would be better if you could add a gif to `extra` folder, and provide a link. ensure that size of gif is not very large it creates problem in loading. And dont add its link to readme directly. just add it to extra folder, Lateron I will create a seperate MD file for gifs.
Aslo a small tip, never miss PR description and mention of issue this PR is for.
Happy contributing. looking forward to see your next commit.

**Comment by srbcheema1** [comment]
use our tool to `crop` this video, that you are using for gif, so that user can focus on main content instead of full screen.
reduce its size using `resize -q 60` and also try to make focus more on commands and terminal. keep your vlc in small size equivalent to size of terminal so that you can swap between two in same area.

**Comment by ujjawalgupta29** [comment]
okay sir. Thanks

**Comment by srbcheema1** [comment]
@ujjawalgupta29 working on it? there are some conflicts in your branch as it is outdated. there are some ways to overcome it. I have mentioned those ways in PR #4 please have a look.

Just a tip. never make a PR from your master branch.

**Comment by srbcheema1** [comment]
@ujjawalgupta29 are you working on it. if any doubt or difficulty please tell. I will resolve those conflicts for you if you are facing any problem. I would say to solve them yourself, it will require some googling but you will really learn a cool thing that will help u a lot in future. you may ping me anytime you want in case of any problem.

**Comment by srbcheema1** [comment]
Closed due to inactivity

**Pull request closed without merging**
